export enum Sector {
    AGRICULTURA = 'AGRICULTURA',
    BIENES_RAICES = 'BIENES_RAICES',
    BANCA = 'BANCA',
    CONSTRUCCION = 'CONSTRUCCION',
    CONSULTORIA = 'CONSULTORIA',
    ENERGIA = 'ENERGIA',
    EDUCACION = 'EDUCACION',
    FINANZAS = 'FINANZAS',
    TECNOLOGIA = 'TECNOLOGIA',
    TURISMO = 'TURISMO',
  }